language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
   directories:
     - $HOME/.composer/cache/files

before_script:
    - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi

script:
    - ant -f build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-continuous static-lint

notifications:
    email: false
    irc: "chat.freenode.net#shopware-dev"

matrix:
  allow_failures:
    - php: 7.1
